### PR TITLE
Added Code of Conduct for Issue 81

### LINKED ISSUE #81: Code Of Conduct
We should Copy the Techlahoma Code of Conduct and include it in this repositories Code of conduct. If you click on insights, then the heart symbol (for community) it will outline some helpful metrics that your repo should embrace, to make the repo more friendly to the community.

### PR DESCRIPTION
**Pull request by mattstub**
Added a Code of Conduct markdown file, this resolves #81 

@dashcraft let me know what you think about this

### CODE REVIEW

**Comment by Jason9199** [comment]
Looks like the link to the included Techlahoma graphic is incorrect.

**Comment by mattstub** [comment]
changed the file name and path to make sure it would find this image once it's uploaded to our /images folder, @Jason9199

**Review by kacollins — CHANGES_REQUESTED** [review]
Remove the image link from the markdown file and then add it back in later when the image exists at that path.

**Comment by mattstub** [comment]
@kacollins the image link has been removed at this time

**Review by kacollins — APPROVED** [review]

**Pull request merged**
