### PR TITLE
Issue #25

### PR DESCRIPTION
**Pull request by julistanley**
Added a section in the Resources tab for the youtube playlist, resolving Issue #25

### CODE REVIEW

**Review by Jason9199 — COMMENTED** [review]
We are currently discussing the best way to include the YouTube playlist in the site, and will provide feedback when that is decided.

**Review by Jason9199 — APPROVED** [review]
Thanks for the contribution.

**Comment by Jason9199** [comment]
@julianstanley did you delete your fork? I am unable to merge in the changes now as they show to be coming from an "unknown repository".

**Comment by julistanley** [comment]
Oh no! Yes, I deleted the fork. A post online claimed that it wouldn't make a difference even before it was approved, but I guess I misread or it was inaccurate. I'll re-fork and re-request

**Pull request closed without merging**
