### PR TITLE
ADD INFO ABOUT AVAILABLE DEV TOOLS IN BROWSER

### LINKED ISSUE #84: Dev Tools
### Outline the Issue

- [] Is the issue a bug?
- [] Is the issue a typo?
- [x] Is the issue a proposed new feature?

### Describe the Issue

- environment-setup.html explains how to install modern web browsers
-all modern web browsers come with developer tools installed by default 
-add some text describing what developer tools are and a link to MDN web site for more information.

### PR DESCRIPTION
**Pull request by egkwong**
## Related Issue

Resolves #84 

### Description

-environment-setup.html explains how to install modern web browsers
-all modern web browsers come with developer tools installed by default
-add some text describing what developer tools are and a link to MDN web site for more information.

### Checklist

- [x] I have read and understand the **CODE OF CONDUCT** as outlined
- [x] I have read the **CONTRIBUTING** document
- [x] I have validating my HTML as outlined in the **CONTRIBUTING** document
- [x] My repository is up to date, and merge conflicts have been resolved
- [x] This pull request relates to an open issue and has been tagged above

### CODE REVIEW

**Review by Jason9199 — CHANGES_REQUESTED** [review]
Good information, and I definitely think we should include this. Please also include information about using the Chrome developer tools https://developer.chrome.com/devtools as well.

**Review by Jason9199 — CHANGES_REQUESTED** [review]
Thank you for including the link to the Chrome Dev Tools. I'd like the new section to read a little better though. I would suggest phrasing the links to both dev tools the same. My preference would be the "For more information" approach. And I think the list you added is probably redundant. My suggestion is to take what you have and stop at the "...just right all in the browser." and then add the two links to the dev tools using the "For more information..."approach like you did for the Chrome Dev Tools.

**Comment by egkwong** [comment]
Cool thanks for the feed back.
The MDN web docs is for all browsers with some info about what developer tools are capable of.
Should I change it to just have links to firefox's dev tools and chrome's dev tools?

**Comment by Jason9199** [comment]
@egkwong You're right about the MDN link. While they use Firefox in all their screenshots, they do include documentation for other browsers in that page as well. I think you're right it should be included. I'll go ahead and approve the changes. Good work!

**Review by Jason9199 — APPROVED** [review]

**Pull request merged**
