### PR TITLE
Slack page for Issue #19

### PR DESCRIPTION
**Pull request by Jason9199**
Slack page for Issue #19

### CODE REVIEW

**Review by CarsonMcKinstry — COMMENTED** [review]
I like this idea!
However, the symbol that you used is a bit intrusive to the normal flow of reading. I would suggest doing some research on the `<sup>` tag, and potentially changing to using that

**Comment by Jason9199** [comment]
Made the changes you requested @CarsonMcKinstry

**Comment by Jason9199** [comment]
@CarsonMcKinstry is there any other changes you would like to see done on this before it's ready for a merge?

**Review by dashcraft — APPROVED** [review]
No issues here, changes made as requested.

**Pull request merged**
