### PR TITLE
Added note to instructions to clarify 'resolves or 'updates' for completed pull requests vs on-going work for issue

### LINKED ISSUE #106: "Resolves" in Pull Request Template
### Outline the Issue

- [ ] Is the issue a bug?
- [ ] Is the issue a typo?
- [ ] Is the issue a proposed new feature?

### Describe the Issue

In the pull request template, `Resolves #` marks the related issue as resolved when the pull request is closed, and that's not always the intended behavior.
https://github.com/FreeCodeCampOKC/fccokc_web/blame/master/PULL_REQUEST_TEMPLATE.md#L9

### Possible Solution

Make it clearer in the instructions to add the issue number after "Resolves #" if this completes the issue and to use "Updates #" for an on-going issue (like #4).

### PR DESCRIPTION
**Pull request by stu7**
## Related Issue

Resolves #106 

### Checklist

- [X] I have read and understand the <a href='https://github.com/FreeCodeCampOKC/fccokc_web/blob/master/CODE_OF_CONDUCT.md'>CODE OF CONDUCT</a> as outlined
- [X] I have read the <a href='https://github.com/FreeCodeCampOKC/fccokc_web/blob/master/CONTRIBUTING.md'>CONTRIBUTING</a> document
- [X] My repository is up to date, and merge conflicts have been resolved
- [x] This pull request relates to an open issue and has been tagged above

### CODE REVIEW

**Review by mattstub — CHANGES_REQUESTED** [review]
@stu7 please make some changes to this pull request. The entire section needs to be updated with instructions on using the correct keywords depending on what the issue is. If the issue will be resolved they need to use a keyword as outlined on the [closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/) help section of github. If the issue is an on-going project the need to make sure the don't use a keyword, but some type of a descriptive word like 'Updates'.

Also please try to follow format, and include your instructions in line with the others not below the section.

**Comment by mattstub** [comment]
@stu7 have you had a chance to address these issues?

**Comment by stu7** [comment]
@mattstub Negative, i've been in/out of town/state on work/business this week/last.  Its on my to do list.

**Comment by stu7** [comment]
@mattstub Are you referring to the "entire section"(s) above the checklist needing updating from your notes or the section in particular (i.e. Resolves #) I already updated, now requiring changes you requested?  Trying to gauge where to best incorporate and make those updates.

**Comment by mattstub** [comment]
@stu7 I was speaking specifically about the changes you made, they need to be altered, see below..

1. Please follow format, and place the instructions at the top of the section, not below like you currently have them.
2. Please reword the instructions you have, there is too much being said in one line. Use something like "If this PR will complete the issue, use the keyword 'Resolves'" and then a second line stating something along those lines for if the PR does not complete the issue it would be a WIP

**Comment by mattstub** [comment]
closing stagnant PR, handled under PR 135

**Pull request closed without merging**
