### PR TITLE
Added parking image modal for Issue 22

### LINKED ISSUE #22: StarSpace46 Parking
Add link to parking map for StarSpace46, available at https://www.starspace46.com/contact/

### PR DESCRIPTION
**Pull request by mattstub**
Added the parking image from StarSpace46, as well as a modal that blows out to give some guidance as to what the shaded areas are in the image. This PR resolves #22

### CODE REVIEW

**Comment by mattstub** [comment]
@CarsonMcKinstry just sending a reminder that this PR is still open

**Comment by CarsonMcKinstry** [comment]
I will take a look at this tonight once i'm on my personal computer

**Comment by mattstub** [comment]
If we want to change the modal out to utilize bootstrap build out I can rework it.. Still new enough to get lost trying to style it with both BS and Grid in mind.

**Comment by CarsonMcKinstry** [comment]
@mstub Well, we aren't using Bootstrap in this repo, so you should be fine to use just regular CSS for it.

One thing I will suggest is to change how things work on mobile. This layout works just fine on desktop and tablet, but on mobile phones, it is a bit small. Issue #22 will stay open for now, so that we can get the stacking correct

**Review by CarsonMcKinstry — APPROVED** [review]

**Pull request merged**
