### PR TITLE
Updated README

### LINKED ISSUE #36: Readme
Add more information to the readme for this repo

### PR DESCRIPTION
**Pull request by skyth3r**
Resolve #36 
Added the following sections:
- Team
- Contributions
- Code of Conduct
- Acknowledgments

### CODE REVIEW

**Comment by skyth3r** [comment]
Resolve #37 
Added Contributing file and a Code of Conduct (might need a few changes)

**Comment by Jason9199** [comment]
This is already being accomplished under Pull Request #47 However keeping this open for review in case any of this can be used in addition to that.

**Comment by skyth3r** [comment]
I was aware of that @Jason9199, but since I had added some more I though the two could be combined.

**Comment by Jason9199** [comment]
As a note in case this eventually gets merged in, please add the .gitignore back as we do not want to delete that.

**Review by CarsonMcKinstry — DISMISSED** [review]
Please add the .gitignore, there isn't really a reason to remove it.

**Comment by skyth3r** [comment]
Added. gitignore back, sorry about that

**Review by mattstub — CHANGES_REQUESTED** [review]
I like where you have gone with this README file, could you make a simple change for us on this however. We would like to narrow down the list of contacts you show on the website to people that can help with the website. This would include Daniel, Kimberly, Carson, Jason and Matt. The others can be removed from the list.

Also could you limit this change to just the README and eliminate the changes to the CONTRIBUTING, we are not looking at changing this here.

Thanks for the contribution @Skyth3r, it's greatly appreciated.

**Comment by skyth3r** [comment]
Sure @mstub

**Comment by skyth3r** [comment]
Changes have been made 👍

**Review by mattstub — APPROVED** [review]
thanks @Skyth3r!

**Pull request merged**
