### PR TITLE
Hacktoberfest: updated slack links and added required info

### PR DESCRIPTION
**Pull request by GeekyShiva**
made all the required changes as requested by : https://github.com/FreeCodeCampOKC/fccokc_web/issues/49 

please check and merge

### CODE REVIEW

**Review by Jason9199 — CHANGES_REQUESTED** [review]
This looks good, thank you. I think the Techlahoma's Community Spaces part that you added is out of place for this page though. Please remove that part.

Edit: Instead of removing that part, please leave it in and in the text indicate that you can follow that link to learn more about Techlahoma's slack. Thank you.

**Comment by GeekyShiva** [comment]
Changes made please review and accept PR..

Thanks

**Review by Jason9199 — APPROVED** [review]

**Comment by Jason9199** [comment]
@GeekyShiva Thanks for the contribution. One piece of feedback, you don't have to submit a commit deleting the file you're changing and then another to add it back in with the changes. You can just make the changes in the file with one commit. Makes it harder to review the changes when it looks like you've changed the whole file because you deleted it completely then added it back in.

**Comment by GeekyShiva** [comment]
noted with thanks

**Pull request merged**
