### PR TITLE
CHANGE SOCIAL ICONS TO BLACK

### LINKED ISSUE #87: BUG: Social Icon Styling
### Outline the Issue

- [x] Is the issue a bug?
- [] Is the issue a typo?
- [] Is the issue a proposed new feature?

### Describe the Issue

When displaying the website in chrome, the social icon styles are not displaying properly, however they seem to work properly in firefox and safari. They are utilizing the anchor tag styling and showing up as a link instead of the defined black styling.

### PR DESCRIPTION
**Pull request by egkwong**
## Related Issue

Resolves #87 

### Description

Turn social icons black.

### Checklist

- [x] I have read and understand the **CODE OF CONDUCT** as outlined
- [x] I have read the **CONTRIBUTING** document
- [x] I have validating my HTML as outlined in the **CONTRIBUTING** document
- [x] My repository is up to date, and merge conflicts have been resolved
- [x] This pull request relates to an open issue and has been tagged above

### Who needs to review this change?

@mstub

### CODE REVIEW

**Comment by mattstub** [comment]
@egkwong checkout this [codepen](https://codepen.io/MattStubenhofer/pen/eEKmjx) this is how the icons are styled, and they still work this way in smaller windows. So the fix needs to bring the icons back to their original intended state. Sorry for leaving this off originally. 

(edit: fixed link here as well)

**Comment by egkwong** [comment]
@mstub the codepen link is broken.

**Comment by mattstub** [comment]
https://codepen.io/MattStubenhofer/pen/eEKmjx that's odd.. here it is again, and ill send it to you on slack as well

**Review by mattstub — CHANGES_REQUESTED** [review]
codepen link referencing the styling should be showing in comments now, please see that for details on what styling the icons have after the break point

**Comment by mattstub** [comment]
@smauer has this resolved back to its original intent. Thanks @egkwong for looking into this, but this PR is no longer needed

**Pull request closed without merging**
