### PR TITLE
Fixes #40

### LINKED ISSUE #40: Projects
Add summaries and links for our GitHub repositories to the projects page

### PR DESCRIPTION
**Pull request by ashwani99**
Add projects listed here https://github.com/FreeCodeCampOKC to projects.html page

### CODE REVIEW

**Review by kacollins — DISMISSED** [review]
This is great! Can you also include the website itself (the fccokc_web repo)? The leads for it are Daniel Ashcraft and Carson McKinstry.

The Twitch Slack Bot is in production, and Jack Kinsey was a lead on it also.

Thanks!

**Comment by ashwani99** [comment]
@kacollins Looks good now? I didn't find Jack Kinsey's GitHub profile so was unable to add it

**Review by mattstub — CHANGES_REQUESTED** [review]
@ashwani99 just some small clerical changes that I can see here, make sure to watch the capitalization of Oklahoma City, and also could we make the project leads name the actual link instead of a standalone link?

// correction here is Jack Kinsey's github profile https://github.com/jackwkinsey

**Comment by ashwani99** [comment]
@mstub Made the changes as you suggested :+1:

**Review by mattstub — COMMENTED** [review]
check out line 69 for the oklahoma city that needs capitalizing. everything else looks good!

**Comment by ashwani99** [comment]
@mstub Done. Sorry for making the minute mistakes.

**Review by mattstub — APPROVED** [review]

**Pull request merged**
