### PR TITLE
Update Slack links

### PR DESCRIPTION
**Pull request by brycejech**
On home page, remove question mark icon, add helper text and link to slack page.
On about page, link to slack page

### CODE REVIEW

**Review by mattstub — CHANGES_REQUESTED** [review]
I may be nitpicky on this but I wonder if it wouldn't sound better if instead of it saying "check out Slack page for more info" it was more along the lines of "check out our guide to getting started with slack" with the embed link on the guide? Thoughts?

**Comment by brycejech** [comment]
Yeah I like that better. I'll update it when I get some time here in the next couple days. I would prefer the link be on the suggested text that reads "getting started with Slack" rather than on the word "guide". You ok with that? Really, I would prefer the whole string "guide to getting started with Slack" be the link, but that's way too long and I don't have any better ideas.
Thanks @mstub!

**Comment by mattstub** [comment]
@brycejech yeah that should be just fine

**Comment by brycejech** [comment]
@mstub I've updated the language about getting started with Slack on the index page. Should be good to go and can close #68 (forgot to close it in my PR)

**Review by mattstub — APPROVED** [review]

**Pull request merged**
